name: Trigger ReadTheDocs Periodic Build
on:
  push:
  schedule:
    - cron: '17 22 * * *'
env:
  BRANCHES: latest
  # Got from RTD project's Integrations admin page
  PROJECT: spinnaker-graphfrontend-combined/148984/
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger
      run: |
        curl -X POST -d "branches=$BRANCHES" -d "token=$TOKEN" \
          https://readthedocs.org/api/v2/webhook/$PROJECT
      env:
        TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
